stuff

diff --git a/stakater-monorepo-package-helm-charts.yaml b/stakater-monorepo-package-helm-charts.yaml
--- a/stakater-monorepo-package-helm-charts.yaml
+++ b/stakater-monorepo-package-helm-charts.yaml
@@ -25,6 +25,7 @@ spec:
         - >
           set -e
 
+          PIPELINE_BOOKMARK_TAG="tekton-git-marker"
           ln -s /tekton/creds/.ssh /root/.ssh;
           git config --global --add safe.directory $(workspaces.source.path);
 
@@ -33,54 +34,64 @@ spec:
           fi
           
 
-          git config user.email $(params.GIT_EMAIL);
+          if [ $(git tag -l "$PIPELINE_BOOKMARK_TAG") ]; then
 
-        
-          pwd;
+            git config user.email $(params.GIT_EMAIL);
 
-          git diff-tree --no-commit-id HEAD --name-only -r;
-
-          git diff-tree --no-commit-id HEAD --name-only -r | while read CHART;
-          do
           
-            echo $CHART;
-            if [ $(basename "$CHART") == "Chart.yaml" ]; then
+            pwd;
 
-              CHART_NAME=$(cat $CHART | awk -F "name: " 'NF>1{print $2;exit; }')
-              echo $CHART_NAME
 
-              CHART_VERSION=$(cat $CHART | awk -F "version: " 'NF>1{print $2;exit; }')
-              echo $CHART_VERSION
+            git diff HEAD..$PIPELINE_BOOKMARK_TAG --name-only -r | while read CHART;
+            do
+            
+              echo $CHART;
+              if [ $(basename "$CHART") == "Chart.yaml" ]; then
 
-              CHART_TAG="$CHART_NAME-$CHART_VERSION"
-              echo $CHART_TAG
-              
-              CHART_DIR=$(dirname $CHART)
-              echo $CHART_DIR
+                CHART_NAME=$(cat $CHART | awk -F "name: " 'NF>1{print $2;exit; }')
+                echo $CHART_NAME
 
-              # check if git tag exists for chart. Should be {Chart.name-chart.version}
-              if [ git rev-parse ${TAG} >/dev/null 2>&1 ]; then
-                  echo "chart version $TAG already exist, wont push helmchart ";
-                  continue
-              fi
+                CHART_VERSION=$(cat $CHART | awk -F "version: " 'NF>1{print $2;exit; }')
+                echo $CHART_VERSION
 
-              CHART_PACKAGE=$(helm package --version $CHART_VERSION -u $CHART_DIR | cut -d":" -f2 | tr -d '[:space:]')
-              echo $CHART_PACKAGE
+                CHART_TAG="$CHART_NAME-$CHART_VERSION"
+                echo $CHART_TAG
+                
+                CHART_DIR=$(dirname $CHART)
+                echo $CHART_DIR
 
-              if [ "$(params.CUSTOM_CA_CERT_PATH)" != "" ]; then
-                  curl -u "${REG_USER}":"${REG_PASSWORD}" $(params.REGISTRY) --upload-file "$CHART_PACKAGE" --cacert $(params.CUSTOM_CA_CERT_PATH)
+                # check if git tag exists for chart. Should be {Chart.name-chart.version}
+                if [ git rev-parse ${TAG} >/dev/null 2>&1 ]; then
+                    echo "chart version $TAG already exist, wont push helmchart ";
+                    continue
+                fi
+
+                CHART_PACKAGE=$(helm package --version $CHART_VERSION -u $CHART_DIR 2>&1)
+                if [ $? -ne 0 ]; then
+                    echo "Error occurred while packaging the Helm chart.";
+                    echo $?;
+                    echo $CHART_PACKAGE;
+                    continue;
+                fi
+
+                CHART_PACKAGE=$(echo "$CHART_PACKAGE" | cut -d":" -f2 | tr -d '[:space:]')
+
+                echo $CHART_PACKAGE
+
+                if [ "$(params.CUSTOM_CA_CERT_PATH)" != "" ]; then
+                    curl -u "${REG_USER}":"${REG_PASSWORD}" $(params.REGISTRY) --upload-file "$CHART_PACKAGE" --cacert $(params.CUSTOM_CA_CERT_PATH)
+                else
+                    curl -u "${REG_USER}":"${REG_PASSWORD}" $(params.REGISTRY) --upload-file "$CHART_PACKAGE" 
+                fi
+
+                git tag -am "Bump version to $CHART_TAG" $CHART_TAG;
+
               else
-                  curl -u "${REG_USER}":"${REG_PASSWORD}" $(params.REGISTRY) --upload-file "$CHART_PACKAGE" 
+                echo "Chart.yaml not found in directory";
               fi
 
-              git tag -am "Bump version to $CHART_TAG" $CHART_TAG;
-
-            else
-              echo "Chart.yaml not found in directory";
-            fi
-
-          done
-
+            done
+          fi
           git push --tags
       command:
         - /bin/bash
